### ISSUE TITLE
Charts missing after upgrade from ubuntu 14.04 to 16.04

### ISSUE THREAD

**Issue by karsta62** [wfrog/wfrog#149]
Any help highly appreciated...

Normal usage of the web ui.
Ubuntu 16.04.2 32bit (old hw)
wfrog 0.8.2-svn
WH1080 station

After upgrade from Ubuntu 14.04 to 16.04 the charts view shows no images. Table view is ok.
All the wfrog logs I find are four years old?? I also find no errors in debug mode.

When loading a missing chart image by rightclik, the browser tells:

_**400. That’s an error.
Your client has issued a malformed or illegal request. That’s all we know.**_

Compared to a working wfrog setup, this one has chart URL's beginning:
**_http://www.google.com/chart?_**
instead of the working:
**_http://chart.apis.google.com/chart?_**

Where should I look to try changing that?

![wfrog-nocharts](https://user-images.githubusercontent.com/21019791/28208321-c8df6e98-6895-11e7-9e77-024c4f0712f7.png)

**Comment by karsta62** [comment]
Nobody else insterested. Strange...

Anyway. I installed a fresh ubuntu 16.04 64bit, and the result is exactly the same. No chart graphics. One difference to the last working setup is that these are 0.8.2-svn.

**Comment by jpuigsegur** [comment]
Hi,

Some time ago there was a message regarding a similar issue and this was the outcome:
> if it can help anyone else here :
> 
>  I replaced "chart.get_url()" on wrenderer/render/chart.py file with (chart.get_url()).replace("http://www.google.com","https://chart.googleapis.com") and now every chart is loading !

Please, can you check if this also solves the problem for you?  

If so we will have to investigate why in certain cases this change is necessary. Some months ago I did some research and the only thing I found is that the API we are using from Google is deprecated (https://developers.google.com/chart/image/) but nothing about changing the domain. 

Regarding the chart API, so far Google says that they do not have any plans to turn off the API we need to think about replacements, since at some point we might end up without graphs for good. In any case, that is not the problem you are encountering.

**Comment by karsta62** [comment]
Thank you so much. 
I found two entries of those and changed both. All looks good, but a little different than before, but that's fine. Only odd thing is that line from bottom left to top right. Where might that come from?
![image](https://user-images.githubusercontent.com/21019791/29377479-9c06c490-82c4-11e7-8da5-3dcf226f3949.png)

**Comment by jpuigsegur** [comment]
Strange. I don't remember seeing this happening before and I don't have any idea of why it might be happening.

**Comment by hjindr** [comment]
Hello,
I have the same problem. My SD card was corrupted. There was raspbian wheezy, the chyrts were OK.
I installed new raspbian stretch and the problem occures.
I can confirm, there must be replaced :(chart.get_url()).replace("http://www.google.com","https://chart.googleapis.com") or (chart.get_url()).replace("http://www.google.com","http://chart.apis.google.com") , both is working.
but there is a failure in the html code :
I found there is a "AA" in html, which makes the line-
the whole code of sample chart is below:

img src="http://chart.apis.google.com/chart?cht=lc&amp;chs=250x150&amp;chd=e:4T0Gv4sn4Ry6pblShrsylfrKXrvYg1m2p5sRi1fMYFTDWsRjODpWd5u-______________________________________________________________fv,AA-t&amp;chco=008000|00000000&amp;chf=bg,s,00000000&amp;chxt=y,x&amp;chxl=1:%7c02/01%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c27/03%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c19/06%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c11/09%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c04/12%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20%7c%20&amp;chxr=0,35.0,85.0&amp;chxs=0,8d7641,10,0,lt%7c1,8d7641,10,0,lt&amp;chls=1.5&amp;chma=10,10,10,10"

If I delete the AA, the chart is correct.
But I donť understand html and also not so good to the  chart.py to find the error.
Can you please investigate it?
Thank you very much.
Best regards Jan

**Comment by jpuigsegur** [comment]
I could reproduce the vertical lines. It seems to be some problem with python versions. However I haven't been able to solve it yet.

**Comment by hjindr** [comment]
My dashboard you can see here : http://hjindr.wz.cz/Pocasi/365days.html
It is the same behaviour like yours, I installed it completely new. The charts looked a bit diferent than before. You can compare it - In this link is saved the html page, which was created with instalation on Raspbian Wheezy (2015)
https://drive.google.com/drive/folders/10Hn2v1HqBvH6e2EY523As7GJZ0XSppFG?usp=sharing
The old installation is still running, but the SD card is somehow not more writable, and the logged temperatures are gone on every restart.

**Comment by debrunner** [comment]
# fix diagram diagonal line
# Use correct color delimiter in get_url_bits()
# https://github.com/wbrp/pygooglechart/commit/143f99284cf51548f5abb609dd06e87f108c4b8e

# fix base Google API url
# https://github.com/grahamu/pygooglechart/commit/cfbfe2e930d5528adcb657af23c66397853dba1f

# fix diagram issues by uninstalling old version and installing newest fixed version form github.com
sudo apt remove python-pygooglechart
sudo pip2 install --upgrade --force-reinstall git+https://github.com/grahamu/pygooglechart.git  # fork with fixed googlechart-URL and fix of diagram diagonal line
pip2 show pygooglechart  # check package

**Comment by karsta62** [comment]
Not sure what the first two "fix" -comments mean or should one do somehting according to them, but I executed the two commands you suggested (apt and pip2). The first one removed wfrog as well which I then reinstalled.
It's true that the diagonal lines disappeared, but so did everything else:
![image](https://user-images.githubusercontent.com/21019791/36629442-74e77356-195e-11e8-81cd-2d6e24b1fd25.png)

After that I tried the original fix of jpuigsegur, but It does not help anymore.
Back to square one. Ideas anyone?

**Comment by debrunner** [comment]
I installed wfrog from github sources on a raspberry pi with those commands:
```
cd /srv
sudo mkdir wfrog
sudo chown pi:pi wfrog

sudo apt install -y python-cheetah                  # Template engine
sudo apt install -y python-lxml                     # XML serialization (compile takes very long on raspberrypi)
sudo apt install -y python-usb                    # (optional pyusb) If your station is USB
sudo apt install -y python-serial                 # (optional pyserial) If your station is serial
sudo apt install -y python-yaml                     # For reading config files (pyyaml)

sudo pip2 install --upgrade --force-reinstall git+https://github.com/grahamu/pygooglechart.git  # fork with fixed googlechart-URL and fix of diagram diagonal line
sudo pip2 install --upgrade pywws  # (optional) for Fine Offset WH1080/WH3080 based stations

cd /srv/wfrog
git clone https://github.com/bitopen/wfrog.git
```

**Comment by karsta62** [comment]
My instance is on x86. I don't think I will try that.
In your chart.py, can you show the line containing the google URL?

**Comment by karsta62** [comment]
I managed to get the graphs back by doing the fix of jpuigsegur properly. The diagonal line still exists.

**Comment by karsta62** [comment]
Got it now. Awesome! Thank you.

**Comment by hjindr** [comment]
Thank you for correction and advices. It is working for me too.
